package cPresentacion;

import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author alex
 */
public class CarnetVacunacionCovid19 extends javax.swing.JPanel {

 
    /**
     * Creates new form CarnetVacunacion
     */
    public CarnetVacunacionCovid19() {
    initComponents();
    }

    //crear constructor para el dni y FNacimiento
    public CarnetVacunacionCovid19(String dni, Date fechaNacimiento) {
        initComponents();
        lblDni.setText("DNI: " + dni);
        // Calcular la edad
        Calendar calendar = Calendar.getInstance();
        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH);
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        
        calendar.setTime(fechaNacimiento);
        int birthYear = calendar.get(Calendar.YEAR);
        int birthMonth = calendar.get(Calendar.MONTH);
        int birthDay = calendar.get(Calendar.DAY_OF_MONTH);

        int edad = year - birthYear;
        if (month < birthMonth || (month == birthMonth && day < birthDay)) {
            edad--;
        }

        // Mostrar la edad en el JLabel
        lblEdad.setText("Edad: " + edad + " años");
        
         // Generar nombre y apellidos aleatorios
        String[] nombres = {"Johel", "Jhon", "Maria", "Ana", "Luis", "Sofía", "Carlos", "Lucía","Alexander"};
        String[] apellidos = {"Lazo","García", "Rodríguez", "González", "Hernández", "Martínez", "López", "Sánchez", "Díaz"};

        Random random = new Random();
        String nombre = nombres[random.nextInt(nombres.length)];
        String apellido1 = apellidos[random.nextInt(apellidos.length)];
        String apellido2 = apellidos[random.nextInt(apellidos.length)];

        String nombreCompleto = nombre + " " + apellido1 + " " + apellido2;

        // Mostrar el nombre y apellidos aleatorios en el JLabel
        lblNombre.setText("Nombre: " + nombreCompleto);
    }

   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        LogoMinsa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        dosis = new javax.swing.JPanel();
        lblImgVacuna = new javax.swing.JLabel();
        lblImgQR = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblVacunacion = new javax.swing.JLabel();
        lblPrimerRefuerzo = new javax.swing.JLabel();
        lblDosis = new javax.swing.JLabel();
        btnComoPDF = new javax.swing.JButton();
        btnComoImagen = new javax.swing.JButton();
        identificate = new javax.swing.JPanel();
        verpasaporte = new javax.swing.JPanel();
        lblingrese = new javax.swing.JLabel();
        lblmen = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnContinuar2 = new javax.swing.JButton();
        verpasaporte1 = new javax.swing.JPanel();
        lblingrese1 = new javax.swing.JLabel();
        lblmen1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnContinuar1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        piepagina = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 134, 229));
        header.setPreferredSize(new java.awt.Dimension(1200, 40));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoMinsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Link.png"))); // NOI18N
        header.add(LogoMinsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));

        jLabel13.setBackground(new java.awt.Color(85, 87, 95));
        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Política de Privacidad / Términos y Condiciones");
        header.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 20));

        btnCerrarSesion.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        header.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        principal.setBackground(new java.awt.Color(243, 244, 246));
        principal.setPreferredSize(new java.awt.Dimension(580, 350));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 41, 47));
        jLabel1.setText("Descarga tu Carné de Vacunación:  ");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        principal.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        dosis.setBackground(new java.awt.Color(255, 255, 255));
        dosis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dosis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgVacuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipox5.png"))); // NOI18N
        dosis.add(lblImgVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 50));

        lblImgQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Commons_QR_code.png"))); // NOI18N
        dosis.add(lblImgQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");
        dosis.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lblDni.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblDni.setForeground(new java.awt.Color(85, 87, 95));
        lblDni.setText("DNI: ");
        dosis.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblEdad.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(85, 87, 95));
        lblEdad.setText("Edad:  ");
        dosis.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));
        dosis.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 240, -1));

        lblVacunacion.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblVacunacion.setForeground(new java.awt.Color(51, 153, 255));
        lblVacunacion.setText("VACUNACIÓN COVID-19 ");
        dosis.add(lblVacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lblPrimerRefuerzo.setBackground(new java.awt.Color(255, 255, 255));
        lblPrimerRefuerzo.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblPrimerRefuerzo.setForeground(new java.awt.Color(0, 255, 51));
        lblPrimerRefuerzo.setText("CON PRIMER REFUERZO ");
        dosis.add(lblPrimerRefuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        lblDosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dosis.png"))); // NOI18N
        dosis.add(lblDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        principal.add(dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 270, 430));

        btnComoPDF.setText("Como PDF");
        principal.add(btnComoPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        btnComoImagen.setText("Como imagen");
        principal.add(btnComoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, -1));

        add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 560));

        identificate.setBackground(new java.awt.Color(249, 249, 249));
        identificate.setPreferredSize(new java.awt.Dimension(620, 350));
        identificate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verpasaporte.setBackground(new java.awt.Color(255, 255, 255));
        verpasaporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verpasaporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblingrese.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblingrese.setText("Tu Vacunación COVID-19 ");
        verpasaporte.add(lblingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        lblmen.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblmen.setText("Certificado COVID-19 ");
        verpasaporte.add(lblmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 35, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(85, 87, 95));
        jLabel19.setText("Visualiza y descarga tu Certificado");
        verpasaporte.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(85, 87, 95));
        jLabel17.setText("de Vacunación COVID-19.");
        verpasaporte.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnContinuar.setBackground(new java.awt.Color(0, 134, 229));
        btnContinuar.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Ver esquema de vacunación");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        verpasaporte.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 239, -1));

        jLabel18.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(85, 87, 95));
        jLabel18.setText("COVID-19.  ");
        verpasaporte.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel26.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(85, 87, 95));
        jLabel26.setText("Esquema de vacunación ");
        verpasaporte.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(85, 87, 95));
        jLabel27.setText("COVID-19 ");
        verpasaporte.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(85, 87, 95));
        jLabel28.setText("Revisa los detalles de tu vacunación ");
        verpasaporte.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnContinuar2.setBackground(new java.awt.Color(0, 134, 229));
        btnContinuar2.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        btnContinuar2.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar2.setText("Ver certificado de vacunación");
        btnContinuar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar2ActionPerformed(evt);
            }
        });
        verpasaporte.add(btnContinuar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 239, -1));

        identificate.add(verpasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 310, 290));

        verpasaporte1.setBackground(new java.awt.Color(255, 255, 255));
        verpasaporte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verpasaporte1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblingrese1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblingrese1.setText("Pasaporte COVID-19 ");
        verpasaporte1.add(lblingrese1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        lblmen1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblmen1.setText("menores de edad");
        verpasaporte1.add(lblmen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 35, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(85, 87, 95));
        jLabel23.setText("Si vas a viajar a alguno de los países");
        verpasaporte1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(85, 87, 95));
        jLabel24.setText("de la Unión Europea, necesitarás tu");
        verpasaporte1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnContinuar1.setBackground(new java.awt.Color(0, 134, 229));
        btnContinuar1.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        btnContinuar1.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar1.setText("Ver pasaporte COVID-19 EU");
        btnContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar1ActionPerformed(evt);
            }
        });
        verpasaporte1.add(btnContinuar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 239, -1));

        jLabel25.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(85, 87, 95));
        jLabel25.setText("Pasaporte Covid.");
        verpasaporte1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        identificate.add(verpasaporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 310, 180));

        add(identificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 620, 560));

        piepagina.setBackground(new java.awt.Color(39, 41, 47));
        piepagina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Copyright © 2022. Desarrollado por la Oficina General de Tecnologías de la Información del Ministerio de Salud.  ");
        piepagina.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Política de Privacidad y Términos y Condiciones.");
        piepagina.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Todos los derechos reservados.");
        piepagina.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        add(piepagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1200, 70));
    }// </editor-fold>//GEN-END:initComponents


    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // Get the JFrame that contains this JPanel
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Dispose of the JFrame
        frame.dispose();

        // Show the Principal window again
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuar1ActionPerformed

    private void btnContinuar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuar2ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Crear una instancia del panel destino
        CarnetVacunacion panelVacunacion = new CarnetVacunacion();

        // Obtener la ventana actual
        JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Reemplazar el contenido de la ventana actual
        ventanaActual.getContentPane().removeAll();
        ventanaActual.getContentPane().add(panelVacunacion);
        ventanaActual.revalidate();
     
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoMinsa;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComoImagen;
    private javax.swing.JButton btnComoPDF;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnContinuar1;
    private javax.swing.JButton btnContinuar2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel dosis;
    private javax.swing.JPanel header;
    private javax.swing.JPanel identificate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblImgQR;
    private javax.swing.JLabel lblImgVacuna;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrimerRefuerzo;
    private javax.swing.JLabel lblVacunacion;
    private javax.swing.JLabel lblingrese;
    private javax.swing.JLabel lblingrese1;
    private javax.swing.JLabel lblmen;
    private javax.swing.JLabel lblmen1;
    private javax.swing.JPanel piepagina;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel verpasaporte;
    private javax.swing.JPanel verpasaporte1;
    // End of variables declaration//GEN-END:variables
}
